In [1]:
pip install tensorflow pandas numpy scikit-learn matplotlib jupyter

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tensorflow in ./.local/lib/python3.13/site-packages (2.21.0)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.3.5)
Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.13/site-packages (1.7.2)
Requirement already satisfied: matplotlib in /opt/anaconda3/lib/python3.13/site-packages (3.10.6)
Requirement already satisfied: jupyter in /opt/anaconda3/lib/python3.13/site-packages (1.1.1)
Requirement already satisfied: absl-py>=1.0.0 in ./.local/lib/python3.13/site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in ./.local/lib/python3.13/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in ./.local/lib/python3.13/site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in ./.local/lib/python3.13/site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in ./.local/lib/python3.13/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in ./.local/lib/python3.13/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in ./.local/lib/python3.13/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.13/site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in ./.local/lib/python3.13/site-packages (from tensorflow) (7.34.1)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/anaconda3/lib/python3.13/site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.13/site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in ./.local/lib/python3.13/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /opt/anaconda3/lib/python3.13/site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /opt/anaconda3/lib/python3.13/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in ./.local/lib/python3.13/site-packages (from tensorflow) (1.80.0)
Requirement already satisfied: keras>=3.12.0 in ./.local/lib/python3.13/site-packages (from tensorflow) (3.13.2)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in ./.local/lib/python3.13/site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in ./.local/lib/python3.13/site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: notebook in /opt/anaconda3/lib/python3.13/site-packages (from jupyter) (7.4.5)
Requirement already satisfied: jupyter-console in /opt/anaconda3/lib/python3.13/site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in /opt/anaconda3/lib/python3.13/site-packages (from jupyter) (7.16.6)
Requirement already satisfied: ipykernel in /opt/anaconda3/lib/python3.13/site-packages (from jupyter) (6.31.0)
Requirement already satisfied: ipywidgets in /opt/anaconda3/lib/python3.13/site-packages (from jupyter) (8.1.7)
Requirement already satisfied: jupyterlab in /opt/anaconda3/lib/python3.13/site-packages (from jupyter) (4.4.7)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/anaconda3/lib/python3.13/site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /opt/anaconda3/lib/python3.13/site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in ./.local/lib/python3.13/site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in ./.local/lib/python3.13/site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: appnope>=0.1.2 in /opt/anaconda3/lib/python3.13/site-packages (from ipykernel->jupyter) (0.1.4)
Requirement already satisfied: comm>=0.1.1 in /opt/anaconda3/lib/python3.13/site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in /opt/anaconda3/lib/python3.13/site-packages (from ipykernel->jupyter) (1.8.16)
Requirement already satisfied: ipython>=7.23.1 in /opt/anaconda3/lib/python3.13/site-packages (from ipykernel->jupyter) (9.7.0)
Requirement already satisfied: jupyter-client>=8.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from ipykernel->jupyter) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /opt/anaconda3/lib/python3.13/site-packages (from ipykernel->jupyter) (5.8.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /opt/anaconda3/lib/python3.13/site-packages (from ipykernel->jupyter) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in /opt/anaconda3/lib/python3.13/site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: psutil>=5.7 in /opt/anaconda3/lib/python3.13/site-packages (from ipykernel->jupyter) (7.0.0)
Requirement already satisfied: pyzmq>=25 in /opt/anaconda3/lib/python3.13/site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: tornado>=6.2 in /opt/anaconda3/lib/python3.13/site-packages (from ipykernel->jupyter) (6.5.1)
Requirement already satisfied: traitlets>=5.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from ipykernel->jupyter) (5.14.3)
Requirement already satisfied: decorator>=4.3.2 in /opt/anaconda3/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in /opt/anaconda3/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.19.2)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in /opt/anaconda3/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.13/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/anaconda3/lib/python3.13/site-packages (from jedi>=0.18.1->ipython>=7.23.1->ipykernel->jupyter) (0.8.5)
Requirement already satisfied: platformdirs>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.5.0)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/lib/python3.13/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel->jupyter) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (3.0.0)
Requirement already satisfied: pure_eval in /opt/anaconda3/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /opt/anaconda3/lib/python3.13/site-packages (from ipywidgets->jupyter) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /opt/anaconda3/lib/python3.13/site-packages (from ipywidgets->jupyter) (3.0.15)
Requirement already satisfied: async-lru>=1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from jupyterlab->jupyter) (2.0.5)
Requirement already satisfied: httpx<1,>=0.25.0 in /opt/anaconda3/lib/python3.13/site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in /opt/anaconda3/lib/python3.13/site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from jupyterlab->jupyter) (2.2.5)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from jupyterlab->jupyter) (2.16.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in /opt/anaconda3/lib/python3.13/site-packages (from jupyterlab->jupyter) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in /opt/anaconda3/lib/python3.13/site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.10.0)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (21.3.0)
Requirement already satisfied: jupyter-events>=0.11.0 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.3)
Requirement already satisfied: nbformat>=5.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (5.10.4)
Requirement already satisfied: overrides>=5.0 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.21.1)
Requirement already satisfied: send2trash>=1.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.0)
Requirement already satisfied: babel>=2.10 in /opt/anaconda3/lib/python3.13/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in /opt/anaconda3/lib/python3.13/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.12.1)
Requirement already satisfied: jsonschema>=4.18.0 in /opt/anaconda3/lib/python3.13/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (4.25.0)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.13/site-packages (from anyio->httpx<1,>=0.25.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in /opt/anaconda3/lib/python3.13/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.28.0)
Requirement already satisfied: python-json-logger>=2.0.4 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.2.1)
Requirement already satisfied: pyyaml>=5.3 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.3)
Requirement already satisfied: rfc3339-validator in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: fqdn in ./.local/lib/python3.13/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in ./.local/lib/python3.13/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in ./.local/lib/python3.13/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.1.0)
Requirement already satisfied: uri-template in ./.local/lib/python3.13/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in ./.local/lib/python3.13/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.10.0)
Requirement already satisfied: beautifulsoup4 in /opt/anaconda3/lib/python3.13/site-packages (from nbconvert->jupyter) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.3.0)
Requirement already satisfied: defusedxml in /opt/anaconda3/lib/python3.13/site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /opt/anaconda3/lib/python3.13/site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /opt/anaconda3/lib/python3.13/site-packages (from nbconvert->jupyter) (3.1.2)
Requirement already satisfied: nbclient>=0.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from nbconvert->jupyter) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/anaconda3/lib/python3.13/site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in /opt/anaconda3/lib/python3.13/site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in /opt/anaconda3/lib/python3.13/site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.21.2)
Requirement already satisfied: lark>=1.2.2 in ./.local/lib/python3.13/site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: cffi>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.0)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.23)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4->nbconvert->jupyter) (2.5)
Requirement already satisfied: arrow>=0.15.0 in /opt/anaconda3/lib/python3.13/site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.4.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
model_df = pd.read_csv("clean_final_data.csv")

model_df["date"] = pd.to_datetime(model_df["date"])

In [4]:
external_cols = [
    "crude_oil_avg_usd",
    "energy_index",
    "non_energy_index",
    "agriculture_index",
    "food_index",
    "fertilizers_index",
    "metals_minerals_index",
    "base_metals_index",
    "precious_metals_index",
    "commodity_total_index"
]

In [5]:
external_cols = [
    "crude_oil_avg_usd", "energy_index", "non_energy_index",
    "food_index", "fertilizers_index", "base_metals_index",
    "precious_metals_index", "fed_funds_rate", "usd_broad_index",
    "us_industrial_production", "us_cpi", "us_10y_treasury_rate",
    "global_policy_uncertainty", "deep_sea_freight_ppi"
]

In [6]:
monthly_external = model_df[
    ["date"] + external_cols
].drop_duplicates()

monthly_external = monthly_external.sort_values("date")

In [7]:
for col in external_cols:
    monthly_external[col + "_lag1"] = (
        monthly_external[col].shift(1)
    )

In [8]:
monthly_external.head()

,date,crude_oil_avg_usd,energy_index,non_energy_index,food_index,fertilizers_index,base_metals_index,precious_metals_index,fed_funds_rate,usd_broad_index,...,fertilizers_index_lag1,base_metals_index_lag1,precious_metals_index_lag1,fed_funds_rate_lag1,usd_broad_index_lag1,us_industrial_production_lag1,us_cpi_lag1,us_10y_treasury_rate_lag1,global_policy_uncertainty_lag1,deep_sea_freight_ppi_lag1
0,2014-01-01,102.0967,131.2182,97.0601,106.5227,105.6653,88.1316,100.5996,0.07,94.464748,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-02-01,104.8267,133.9666,97.9067,108.2873,105.6094,86.8503,105.0007,0.07,94.645582,...,105.6653,88.1316,100.5996,0.07,94.464748,100.1599,235.288,2.858095,115.257559,263.0
4,2014-03-01,104.0400,130.6676,99.9456,113.8253,102.5986,84.4461,107.2837,0.08,94.440821,...,105.6094,86.8503,105.0007,0.07,94.645582,100.9168,235.547,2.709474,101.147273,262.2
6,2014-04-01,104.8667,130.6783,99.9672,112.3142,94.9084,87.0879,103.9296,0.09,93.995550,...,102.5986,84.4461,107.2837,0.08,94.440821,101.8942,236.028,2.723333,114.652379,262.1
8,2014-05-01,105.7133,132.3273,99.5266,112.0518,96.0311,88.5446,102.9955,0.09,93.670029,...,94.9084,87.0879,103.9296,0.09,93.995550,101.9928,236.468,2.705238,110.450150,263.3

In [9]:
lag_columns = [
    "date"
] + [col + "_lag1" for col in external_cols]

In [10]:
monthly_external_lagged = monthly_external[
    lag_columns
].copy()

In [11]:
monthly_external_lagged.head()

,date,crude_oil_avg_usd_lag1,energy_index_lag1,non_energy_index_lag1,food_index_lag1,fertilizers_index_lag1,base_metals_index_lag1,precious_metals_index_lag1,fed_funds_rate_lag1,usd_broad_index_lag1,us_industrial_production_lag1,us_cpi_lag1,us_10y_treasury_rate_lag1,global_policy_uncertainty_lag1,deep_sea_freight_ppi_lag1
0,2014-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-02-01,102.0967,131.2182,97.0601,106.5227,105.6653,88.1316,100.5996,0.07,94.464748,100.1599,235.288,2.858095,115.257559,263.0
4,2014-03-01,104.8267,133.9666,97.9067,108.2873,105.6094,86.8503,105.0007,0.07,94.645582,100.9168,235.547,2.709474,101.147273,262.2
6,2014-04-01,104.0400,130.6676,99.9456,113.8253,102.5986,84.4461,107.2837,0.08,94.440821,101.8942,236.028,2.723333,114.652379,262.1
8,2014-05-01,104.8667,130.6783,99.9672,112.3142,94.9084,87.0879,103.9296,0.09,93.995550,101.9928,236.468,2.705238,110.450150,263.3

In [12]:
model_df = pd.merge(
    model_df,
    monthly_external_lagged,
    on="date",
    how="left"
)

In [13]:
print(model_df.shape)

(4668, 37)

In [14]:
model_df = model_df.dropna(
    subset=[col + "_lag1" for col in external_cols]
)

In [15]:
print(model_df.shape)

(4636, 37)

In [16]:
model_df = model_df.drop(
    columns=external_cols
)

In [17]:
print(model_df.shape)

(4636, 23)

In [18]:
model_df["log_primaryValue"] = np.log1p(
    model_df["primaryValue"]
)

In [19]:
model_df[
    ["primaryValue", "log_primaryValue"]
].head()

   primaryValue  log_primaryValue
2  5.539307e+09         22.435135
3  4.647254e+09         22.259542
4  5.524368e+09         22.432435
5  4.913932e+09         22.315340
6  5.414486e+09         22.412344

In [20]:
model_df = model_df.drop(
    columns=["trade_value_lag12", "lag12_date"],
    errors="ignore"
)

In [21]:
lag_lookup = model_df[
    ["country_name", "flowCode", "date", "primaryValue"]
].copy()

In [22]:
lag_lookup["date"] = (
    lag_lookup["date"] + pd.DateOffset(months=12)
)

lag_lookup = lag_lookup.rename(
    columns={"primaryValue": "trade_value_lag12"}
)

In [23]:
model_df = model_df.merge(
    lag_lookup,
    on=["country_name", "flowCode", "date"],
    how="left"
)

In [24]:
seasonal_model_df = model_df.dropna(
    subset=["trade_value_lag12"]
).copy()

In [25]:
print(seasonal_model_df.shape)

(4196, 25)

In [26]:
seasonal_model_df_encoded = pd.get_dummies(
    seasonal_model_df,
    columns=["country_name", "flowCode"],
    drop_first=True
)

In [27]:
print(seasonal_model_df_encoded.shape)

(4196, 41)

In [28]:
seasonal_model_df_encoded.to_csv(
    "seasonal_model_df_encoded.csv",
    index=False
)

print("Dataset saved successfully.")

Dataset saved successfully.

In [29]:
import os

print(os.path.exists("seasonal_model_df_encoded.csv"))

True